hyperparameters:
    model_name: 'yolov8n'
    epochs: 150
    batch: 16
    imgsz: 640
    save_period: 5
    mixup: 0.3
    device: 'cpu' # TODO: "mpl" is slower - do not understand why
    mosaic: 1.0